apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-produkt-pvc
  labels:
    app: backend-produkt
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
