apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-produkt-hpa
  labels:
    app: backend-produkt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-produkt
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
