apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-produkt-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ../../backend/uploads
