apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
data:
  REACT_APP_BACKEND_URL: "http://{{ include "mychart.backendName" . }}:{{ .Values.backend.service.port }}"
