apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
