apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  labels:
    app: keycloak
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
