apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        email VARCHAR(80) UNIQUE NOT NULL,
        nickname VARCHAR(50) UNIQUE NOT NULL
    );

    CREATE TABLE IF NOT EXISTS bouquet (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        price FLOAT NOT NULL CHECK (price > 0),
        image_url VARCHAR(255)
    );

    CREATE TABLE IF NOT EXISTS cart (
        id SERIAL PRIMARY KEY,
        user_id INT REFERENCES users(id) ON DELETE CASCADE,
        bouquet_id INT REFERENCES bouquet(id) ON DELETE CASCADE,
        quantity INT DEFAULT 1
    );
