apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
data:
  REACT_APP_PRODUCT_SERVICE_URL: "http://localhost:5001"
  REACT_APP_CART_SERVICE_URL: "http://localhost:5002"
