apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: keycloak
type: Opaque
data:
  admin-user: {{ .Values.keycloak.admin.user | b64enc | quote }}
  admin-password: {{ .Values.keycloak.admin.password | b64enc | quote }}
