apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgres.user .Values.postgres.password (include "mychart.postgresName" .) (.Values.postgres.service.port | toString) .Values.postgres.database | b64enc | quote }}
  REDIS_URL: {{ printf "redis://%s:%s" (include "mychart.redisName" .) (.Values.redis.service.port | toString) | b64enc | quote }}
  KEYCLOAK_SERVER_URL: {{ printf "http://%s:%d/auth" (include "mychart.keycloakName" .) .Values.keycloak.service.port | b64enc | quote }} # http://keycloak:8080/auth
  KEYCLOAK_REALM: "bXlyZWFsbQ==" # myrealm
  KEYCLOAK_CLIENT_ID: "bXljbGllbnQ=" # myclient
