apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.backend.pv.hostPath | quote }}
