apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.backendName" . }}
  labels:
    app: backend
  annotations:
    prometheus.io/scrape: "true" # Określa, że Prometheus ma zbierać metryki z tej usługi
    prometheus.io/port: "5001" # Określa port, z którego Prometheus ma pobierać metryki
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
