apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  labels:
    app: backend
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
