apiVersion: v1
kind: Secret
metadata:
  name: backend-cart-secret
  labels:
    app: backend-cart
type: Opaque
data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9kYg==" # postgresql://user:password@postgres:5432/db
  REDIS_URL: "cmVkaXM6Ly9yZWRpczo2Mzc5" # redis://redis:6379
  KEYCLOAK_SERVER_URL: "aHR0cDovL2tleWNsb2FrOjgwODAvYXV0aA==" # http://keycloak:8080/auth
  KEYCLOAK_REALM: "bXlyZWFsbQ==" # myrealm
  KEYCLOAK_CLIENT_ID: "bXljbGllbnQ=" # myclient
