apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-cart-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-cart
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
