name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Logowanie do Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Budowanie i push obrazu frontend
      run: |
        docker build --no-cache -t myapp-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest

    - name: Budowanie i push obrazu backend
      run: |
        docker build --no-cache -t myapp-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest
